# Generated by Django 4.0.4 on 2022-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_alter_comment_created_on_alter_post_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateField(),
        ),
    ]
