# Generated by Django 4.0.4 on 2022-05-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_alter_rareuser_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rareuser',
            name='admin_approval',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postuser', to='rareapi.rareuser'),
        ),
    ]
